server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
logging:
  level:
    org:
      springframework: INFO
    #        cloud:
    #          gateway: ERROR
    #        security: TRACE
    reactor.netty.http.client: ERROR
